name: Run Microservices and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-e-build-microservicos:
    runs-on: ubuntu-latest

    steps:
    #subindo o codigo pra esteira
    - name: Checkout code
      uses: actions/checkout@v3

    # 2.Setando o node
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Versao 18, no front tmb

#    # 3. Instalar dependências para lint
    - name: Install dependencies
      run: yarn install

    - name: Rodando Lint para cada microservico
      run: |
        docker-compose exec -T api_gateway yarn lint
        docker-compose exec -T users_microservice yarn lint
        docker-compose exec -T application_microservice yarn lint
        
    # 4. Lint -> Ainda a checar - comentado para testar o funcionamento da esteira
 #   - name: Run lint
 #     run: yarn lint

 

    # 5. Configurar o Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # 6. Subindo docker compose
    - name: Start Docker Compose
      run: docker-compose up -d

    # 7. Verificar os serviços
    - name: Check services
      run: docker-compose ps

    # 8. Rodar testes em cada microserviço
#    - name: Run tests
#      run: |
#        docker-compose exec -T api_gateway yarn test
#        docker-compose exec -T users_microservice yarn test
#        docker-compose exec -T application_microservice yarn test


    # 9. Encerrar os serviços
    - name: Stop Docker Compose
      if: always()
      run: docker-compose down
